# SPDX-FileCopyrightText: 2020 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

################################### Default Configuration ############################

baseurl = "https://ev.hedgedoc.org/"
title = "HedgeDoc e.V."
enableEmoji = true

# post excert
summarylength = "20"

# google analytics
googleAnalytics = "" # Ex: UA-123-45

# disable language
disableLanguages = [] # disable language from here
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true

########################### Default parameters ##########################

[params]
logo = "images/banner/hedgedoc_banner_color_horizontal.svg"
logo_width = "100px"
logo_height = "25px"
author = "HedgeDoc e.V."

[Languages.de.params]
copyright = "Erstellt von den HedgeDoc-Entwicklern. Mit ![love](/images/heart.svg)️ und [Hugo](https://gohugo.io/)."
description = "Informationen über den HedgeDoc e.V."

[Languages.en.params]
copyright = "By the HedgeDoc developers. Made with ![love](/images/heart.svg)️ and [Hugo](https://gohugo.io/)."
description = "Informationen about the HedgeDoc e.V."

[[Languages.de.Menus.footer]]
Name="Impressum"
Url="/impressum"

[[Languages.en.Menus.footer]]
Name="Imprint"
Url="/impressum"

[Languages.de]
languageName = "Deutsch"
languageCode = "de-de"
contentDir = "content/german"
weight = 1

[Languages.en]
languageName = "English"
languageCode = "de-de"
contentDir = "content/english"
weight = 2


[markup.goldmark.renderer]
unsafe= true
