# SPDX-FileCopyrightText: 2020 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Check links

on:
  push:
  schedule:
    - cron: "0 3 * * *"

jobs:
  check-links:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # renovate: datasource=github-releases depName=gohugoio/hugo versioning=semver
          hugo-version: "0.125.7"
          extended: true

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci && npm install broken-link-checker

      - name: Run Hugo
        run: hugo server -e production --minify -b http://127.0.0.1:1313/ & sleep 5

      - name: Check for broken links
        # GitHub is excluded because we otherwise run into rate-limits and get many HTTP_429 link errors.
        # Twitter (via our redirector) is excluded because they seem to block such checks, resulting in HTTP_400 errors.
        run: node_modules/.bin/blc http://127.0.0.1:1313/ -ro --exclude "https://github.com/*" --exclude "https://docs.github.com/*" --exclude "https://social.hedgedoc.org/twitter"  --exclude "https://hackmd.io"
